name: Update REAPER API Documentation

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: |
          cd generator
          bun install
          
      - name: Generate API documentation
        run: |
          cd generator
          bun generate
          
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet luadoc/reaper-api.lua; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in reaper-api.lua"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in reaper-api.lua"
          fi
          
      - name: Get current date
        if: steps.check_changes.outputs.changes == 'true'
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update REAPER API documentation (${{ steps.date.outputs.date }})"
          title: "🤖 Update REAPER API Documentation - ${{ steps.date.outputs.date }}"
          body: |
            ## Automated REAPER API Documentation Update
            
            This PR was automatically generated by the GitHub workflow.
            
            ### Changes
            - Updated `luadoc/reaper-api.lua` with the latest REAPER API documentation
            - Generated from: https://www.reaper.fm/sdk/reascript/reascripthelp.html
            - Date: ${{ steps.date.outputs.date }}
            
            ### Summary
            The REAPER API documentation has been refreshed with any new functions, updated signatures, or improved descriptions from the official documentation.
            
            Please review the changes and merge if they look correct.
          branch: update-api-docs-${{ steps.date.outputs.date }}
          delete-branch: true
          draft: false
          labels: |
            documentation
            automated
            api-update
          
      - name: Output PR information
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          echo "Created pull request for API documentation updates"
          echo "When this PR is merged, a new release will be automatically created"
          echo "Release version will be based on the REAPER version extracted from the updated lua file"
